### ISSUE TITLE
ICMP messages not forwarded to guest

### ISSUE THREAD

**Issue by MagnusS** [moby/vpnkit#193]
ICMP messages such as `Destination unreachable` or `Time exceeded` are not forwarded back to the guest. 

This e.g. breaks `traceroute`

(related to #28)

**Comment by arpadkun** [comment]
It seems the icmp messages are already forwarded to the guest (mentioned in #1381), the latency measured from the guest is accurate, but the TTL settings seem to be still a problem. MTR or any other ICMP based traceroute fails to work. UDP still not working. Any update in regard this issue please?

**Comment by djs55** [comment]
In #302 ICMP messages are forwarded to the VM in some cases, which is enough to make `traceroute` work on Mac (but not Windows).
