### ISSUE TITLE
Include an HTTP proxy

### ISSUE THREAD

**Issue by djs55** [moby/vpnkit#20]
We currently terminate TCP flows and connect them to outgoing socket connections. For the special case of HTTP we could forward the connections to the upstream HTTP proxy (if the host has one). We could start by simply proxying the TCP connections and then experiment with running a full HTTP proxy if necessary.

This involves
- figuring out how to monitor the host OS's HTTP proxy settings
- writing the proxy code

**Comment by yomimono** [comment]
See https://github.com/mirage/ocaml-cohttp/issues/501 for a summation of upstream work in `ocaml-cohttp` which would be helpful to have implemented.

**Comment by samoht** [comment]
@djs55 I guess this issue can now be closed?

**Comment by djs55** [comment]
@samoht thanks for the reminder!

For future reference there are [instructions](https://github.com/moby/vpnkit/blob/6233545bf34ace4ede51588c9279d38256ea4502/docs/transparent-http-proxy.md) describing how to use the transparent HTTP proxy in the `docs/` directory.
