### ISSUE TITLE
Move preferred IP into new protocol command

### ISSUE THREAD

**Issue by MagnusS** [moby/vpnkit#209]
The vmnet protocol used by vpnkit and hyperkit should have a `preferred_ip` command to request a specific IP with the uuid. See also https://github.com/docker/vpnkit/pull/207#discussion_r110441704

Changes needed:
* [x] Vpnkit: protocol needs to be extended to include a [new command](https://github.com/docker/vpnkit/blob/master/src/hostnet/vmnet.mli#L48)
* [x] Hyperkit: accept a `preferred_ip=` option in `pci_virtio_net_vpnkit` and send the new command to vpnkit if present

**Comment by MagnusS** [comment]
I'm working on adding a new `Preferred_ipv4` command to `vpnkit` now. Since the first packet with the command has a fixed size and only has room for the UUID, I'll have to extend it with 4 bytes for the IP. This will not be backwards compatible and requires a protocol version bump. 

Alternatively, I could try to keep the code compatible by making the buffer length dynamic -- but unless bumping the version will be problematic I'm not sure it's worth the restructuring this would require.

**Comment by djs55** [comment]
There aren't very many other implementations of this protocol. The only other one is in `com.docker.vmnetd` in D4M which we can update easily enough. Will it be easy to probe the version in a way that will work with both old and new versions? That's all we need to trigger an automatic upgrade. Ideally we'd keep the version exchange messages the same format to keep this easy.

**Comment by MagnusS** [comment]
Fixed in https://github.com/moby/vpnkit/pull/277 and https://github.com/moby/hyperkit/pull/154, so closing this issue.
