### ISSUE TITLE
HTTP proxy: excessive buffering exception

### ISSUE THREAD

**Issue by djs55** [moby/vpnkit#227]
I was `docker pull ubuntu` and the connection seemed to have stalled. I then saw
```
com.docker.vpnkit: [WARNING] Possibly unexpected exeption Channel.Make(Flow).Write_error(1014511856) in proxy
```
-- perhaps there's a missing flush in the proxy loop, causing the ubuntu image to be entirely buffered in memory?

**Comment by djs55** [comment]
I manually built bcc33edcaebf0817dc5af3505869f35a71d30f25 and it worked fine -- could there be a library difference between the CI version and the local version?

**Comment by djs55** [comment]
Actually it looks like it's my fault -- my wifi is very unreliable and slow.

**Comment by justincormack** [comment]
Sounds like an excellent test case. Lots of people have terrible networking, eg large enterprises!
