### ISSUE TITLE
Write a top-level document explaining vpnkit's components

### ISSUE THREAD

**Issue by yomimono** [moby/vpnkit#23]
A document (perhaps a README.md at the `vpnkit/src` level) describing the functions of individual components would be useful.  Currently the role of `com.docker.slirp` vs `hostnet`, for example, is rather opaque.

**Comment by samoht** [comment]
I think this is now done, as `doc/` contains various intersting docs, especially: https://github.com/moby/vpnkit/blob/master/docs/ethernet.md
