### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by MagnusS** [moby/vpnkit#24]
There are currently no build instructions in the README.

**Comment by samoht** [comment]
The build instructions are currently very involved ... I think the simplest path would be to extract the sequence of `pins` from `circle.yml` and put that in the Makefile. And `circle.yml` could just call it directly.

**Comment by MagnusS** [comment]
Build instructions are now in the [README](https://github.com/moby/vpnkit/blob/master/README.md#building-on-unix) so closing this issue.
