### ISSUE TITLE
Guest gets bogus ICMP echo replies

### ISSUE THREAD

**Issue by ranxxerox** [moby/vpnkit#261]
When using the default install of Docker for Mac (Version 17.06.0-ce-mac19 (18663)), I've run into an issue where the guest will send replies for ICMP echo requests sent to destinations which do not exist:

From the host:
> $ ping -c 3 10.255.255.255
> PING 10.255.255.255 (10.255.255.255): 56 data bytes
> Request timeout for icmp_seq 0
> Request timeout for icmp_seq 1
> 
> --- 10.255.255.255 ping statistics ---
> 3 packets transmitted, 0 packets received, 100.0% packet loss

From the guest:
> / # ping -c 3 10.255.255.255
> PING 10.255.255.255 (10.255.255.255): 56 data bytes
> 64 bytes from 10.255.255.255: seq=0 ttl=38 time=0.334 ms
> 64 bytes from 10.255.255.255: seq=1 ttl=38 time=0.367 ms
> 64 bytes from 10.255.255.255: seq=2 ttl=38 time=0.410 ms
> 
> --- 10.255.255.255 ping statistics ---
> 3 packets transmitted, 3 packets received, 0% packet loss
> round-trip min/avg/max = 0.334/0.370/0.410 ms

guest route table:
> / # ip route show
> default via 192.168.65.1 dev eth0  src 192.168.65.2  metric 204 
> 172.17.0.0/16 dev docker0  src 172.17.0.1 
> 192.168.65.0/24 dev eth0  src 192.168.65.2  metric 204

**Comment by MagnusS** [comment]
ICMP is not proxied by VPNKit yet. The ping replies you see are actually from the internal gateway at 192.168.65.1. It currently replies to all requests it receives so it will look like you get a response with a very low RTT from any IP that is outside the default gateway. I'm closing this issue as it is already tracked by #28.
