### ISSUE TITLE
Reduce the number of dependencies on forked packages.

### ISSUE THREAD

**Issue by yomimono** [moby/vpnkit#27]
vpnkit depends on custom versions of the following packages:
- charrua-core
- lwt
- mirage-types-lwt
- mirage-types
- tcpip

If possible, we should reduce or eliminate these by upstreaming our changes or changing our code to conform with upstream changes.

**Comment by dsheets** [comment]
The `lwt` fork is likely not necessary for vpnkit but is tracked by ocsigen/lwt#215.

**Comment by samoht** [comment]
Work in progress in #262
