### ISSUE TITLE
VPNKIT huge memory consumption, exhausting hard disk bandwitdh when swapping

### ISSUE THREAD

**Issue by CdeMills** [moby/vpnkit#374]
Hello,
context: Windows 10 platform,
Version: 18.03.0-ce
API version: 1.37
Go version: go1.9.4
Git commit: 0520e24
Built: Wed Mar 21 23:06:28 2018
OS/Arch: windows/amd64
Experimental: false
Orchestrator: swarm

The docker container is based on fedora27, created as
docker create -t --name fedora --publish 2242:22 --publish 4732:3389 --init --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -cap-add=NET_ADMIN --device=/dev/net/tun fedora27 /usr/bin/systemctl

with systemctl coming from https://github.com/gdraheim/docker-systemctl-replacement

The only enabled service is sshd; once the container is started I launch a graphical session with x2go server and a get a full linux environment running on top of Windows10.

After around two hours, the hard disk start doing continuous noise, and vpnkit.exe (in Windows) start consuming all the disk bandwidth. At this time the x2go client becomes unresponsive and disconnects. The only option is to stop the container, kill vpnkit, stop docker. Sometimes the x2go client becomes unresponsive too, requiring a machine reboot.

This occured two times this week.

Is there some way to limit vpnkit memory consumption ?

Regards

Pascal

**Comment by djs55** [comment]
This is the same as https://github.com/moby/vpnkit/issues/371 

There's a candidate fix available. If you'd like to try it before it's officially released there are instructions here: https://github.com/moby/vpnkit/issues/371#issuecomment-390248401
