### ISSUE TITLE
Q: recommended way for disabling --host-ip

### ISSUE THREAD

**Issue by AkihiroSuda** [moby/vpnkit#449]
`--host-ip 0.0.0.0` seems fine for disabling `--host-ip`, but it does not seem documented.
Is `--host-ip 0.0.0.0` officially supported way?

**Comment by AkihiroSuda** [comment]
ping @djs55 ^^

**Comment by djs55** [comment]
I think this is fine. I'll add a patch to make this more obvious and add some documentation.

**Comment by AkihiroSuda** [comment]
Thanks!
